services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    container_name: tinvest-analytics-frontend-nginx
    restart: unless-stopped
    ports:
      - '8082:80'
    #    volumes:
    #      - ./dist:/usr/share/nginx/html
    env_file:
      - .env
